version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_BASE=http://localhost:3000/api
    networks:
      - frontend-network
    command: npm run dev

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_API_BASE=http://localhost:3000/api
    networks:
      - frontend-network
    restart: unless-stopped

networks:
  frontend-network:
    driver: bridge 