version: '3.8'

services:
  app-dev:
    container_name: nest-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    ports:
      - "3000:3000"
      - "9229:9229"
    command: npm run start:dev
    depends_on:
      - db
    restart: always

  app-prod:
    container_name: nest-app-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "5000:5000"
    command: npm run start:prod
    depends_on:
      - db

  db:
    container_name: nest-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: 